# Generated by Django 3.2.25 on 2025-09-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('max', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_capacity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Car Types',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('interested_in', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='zones/')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_type', models.CharField(choices=[('ONE_WAY', 'One Way'), ('ROUND_TRIP', 'Round Trip')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.car')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('PAYPAL', 'PayPal'), ('CASH_ON_ARRIVAL', 'Cash on Arrival'), ('STRIPE', 'Stripe')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='core.zone')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='core.cartype'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_country', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_company', models.CharField(blank=True, max_length=200, null=True)),
                ('pickup_date_time', models.DateTimeField()),
                ('return_date_time', models.DateTimeField()),
                ('date_capture', models.DateTimeField(auto_now_add=True)),
                ('how_people', models.PositiveIntegerField(default=1)),
                ('one_way', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('trip_type', models.CharField(blank=True, max_length=20, null=True)),
                ('car_id', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.car')),
                ('dropoff_location1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_location1_bookings', to='core.hotel')),
                ('dropoff_location2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_location2_bookings', to='core.hotel')),
                ('pickup_location1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_location1_bookings', to='core.hotel')),
                ('pickup_location2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_location2_bookings', to='core.hotel')),
            ],
        ),
    ]
