# Generated by Django 3.2.25 on 2025-10-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subscribe_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=50)),
                ('content', models.TextField()),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.whatsappconversation')),
            ],
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversations', to='core.contact'),
        ),
    ]
